// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQLh_zddqEeebowRadOO-JAwEHTZkpXHw',
    appId: '1:788361854716:web:47f90ed9f1a2cd040d6179',
    messagingSenderId: '788361854716',
    projectId: 'skycachefiles',
    authDomain: 'skycachefiles.firebaseapp.com',
    storageBucket: 'skycachefiles.appspot.com',
    measurementId: 'G-V94686VQWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQhfKtOyaEtb7JioUgCTt_ZHv2P_7DuA',
    appId: '1:788361854716:android:1830b371d9e67fb90d6179',
    messagingSenderId: '788361854716',
    projectId: 'skycachefiles',
    storageBucket: 'skycachefiles.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQLh_zddqEeebowRadOO-JAwEHTZkpXHw',
    appId: '1:788361854716:web:7df7eb920d4615f30d6179',
    messagingSenderId: '788361854716',
    projectId: 'skycachefiles',
    authDomain: 'skycachefiles.firebaseapp.com',
    storageBucket: 'skycachefiles.appspot.com',
    measurementId: 'G-L1GJ6PW91D',
  );
}
